version: '3.3'
services:
  app:
    build: 
      context: .
      ports:
      - "8081:8081"
    image: ocr-flask
    container_name: ocr-container
    ports:
    - "8081:8081"
    stdin_open: true 
    tty: true